# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_frechet_decide_dv <- function(t1, t2, eps) {
    .Call(`_frechet_internal_frechet_decide_dv`, t1, t2, eps)
}

internal_frechet_decide_bb <- function(t1, t2, eps) {
    .Call(`_frechet_internal_frechet_decide_bb`, t1, t2, eps)
}

internal_createGridDataset <- function() {
    .Call(`_frechet_internal_createGridDataset`)
}

internal_addTrajectory <- function(gds, m) {
    .Call(`_frechet_internal_addTrajectory`, gds, m)
}

internal_clearDataset <- function(gds) {
    .Call(`_frechet_internal_clearDataset`, gds)
}

internal_createIndex_dv <- function(gds, meshSize) {
    .Call(`_frechet_internal_createIndex_dv`, gds, meshSize)
}

internal_gridRangeQuery <- function(gds, m, eps, materialize = TRUE) {
    .Call(`_frechet_internal_gridRangeQuery`, gds, m, eps, materialize)
}

