# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_frechet_decide_dv <- function(t1, t2, eps) {
    .Call(`_frechet_internal_frechet_decide_dv`, t1, t2, eps)
}

internal_frechet_decide_bb <- function(t1, t2, eps) {
    .Call(`_frechet_internal_frechet_decide_bb`, t1, t2, eps)
}

internal_prepareRangeQueryDataset <- function(l) {
    .Call(`_frechet_internal_prepareRangeQueryDataset`, l)
}

