all:
	g++ -o plain plain.cpp -Wall -std=c++11
	g++ -o bg bg.cpp -Wall -std=c++11
	g++ -o grid grid.cpp -Wall -std=c++11
	g++ -o spatial_index spatial_index.cpp -Wall -std=c++11

clean:
	rm plain bg grid spatial_index

