// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// internal_frechet_decide_dv
bool internal_frechet_decide_dv(NumericMatrix& t1, NumericMatrix& t2, double eps);
RcppExport SEXP _frechet_internal_frechet_decide_dv(SEXP t1SEXP, SEXP t2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_frechet_decide_dv(t1, t2, eps));
    return rcpp_result_gen;
END_RCPP
}
// internal_frechet_decide_bb
bool internal_frechet_decide_bb(NumericMatrix& t1, NumericMatrix& t2, double eps);
RcppExport SEXP _frechet_internal_frechet_decide_bb(SEXP t1SEXP, SEXP t2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_frechet_decide_bb(t1, t2, eps));
    return rcpp_result_gen;
END_RCPP
}
// internal_prepareRangeQueryDataset
size_t internal_prepareRangeQueryDataset(List& l);
RcppExport SEXP _frechet_internal_prepareRangeQueryDataset(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_prepareRangeQueryDataset(l));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_frechet_internal_frechet_decide_dv", (DL_FUNC) &_frechet_internal_frechet_decide_dv, 3},
    {"_frechet_internal_frechet_decide_bb", (DL_FUNC) &_frechet_internal_frechet_decide_bb, 3},
    {"_frechet_internal_prepareRangeQueryDataset", (DL_FUNC) &_frechet_internal_prepareRangeQueryDataset, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_frechet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
