// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// internal_frechet_decide_dv
bool internal_frechet_decide_dv(NumericMatrix& t1, NumericMatrix& t2, double eps);
RcppExport SEXP _frechet_internal_frechet_decide_dv(SEXP t1SEXP, SEXP t2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_frechet_decide_dv(t1, t2, eps));
    return rcpp_result_gen;
END_RCPP
}
// internal_frechet_decide_bb
bool internal_frechet_decide_bb(NumericMatrix& t1, NumericMatrix& t2, double eps);
RcppExport SEXP _frechet_internal_frechet_decide_bb(SEXP t1SEXP, SEXP t2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_frechet_decide_bb(t1, t2, eps));
    return rcpp_result_gen;
END_RCPP
}
// internal_createGridDataset
size_t internal_createGridDataset();
RcppExport SEXP _frechet_internal_createGridDataset() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(internal_createGridDataset());
    return rcpp_result_gen;
END_RCPP
}
// internal_addTrajectory
size_t internal_addTrajectory(size_t gds, NumericMatrix& m);
RcppExport SEXP _frechet_internal_addTrajectory(SEXP gdsSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type gds(gdsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_addTrajectory(gds, m));
    return rcpp_result_gen;
END_RCPP
}
// internal_clearDataset
size_t internal_clearDataset(size_t gds);
RcppExport SEXP _frechet_internal_clearDataset(SEXP gdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type gds(gdsSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_clearDataset(gds));
    return rcpp_result_gen;
END_RCPP
}
// internal_createIndex_dv
bool internal_createIndex_dv(size_t gds);
RcppExport SEXP _frechet_internal_createIndex_dv(SEXP gdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type gds(gdsSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_createIndex_dv(gds));
    return rcpp_result_gen;
END_RCPP
}
// internal_gridRangeQuery
List internal_gridRangeQuery(size_t gds, NumericMatrix m, double eps, bool materialize);
RcppExport SEXP _frechet_internal_gridRangeQuery(SEXP gdsSEXP, SEXP mSEXP, SEXP epsSEXP, SEXP materializeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type gds(gdsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type materialize(materializeSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_gridRangeQuery(gds, m, eps, materialize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_frechet_internal_frechet_decide_dv", (DL_FUNC) &_frechet_internal_frechet_decide_dv, 3},
    {"_frechet_internal_frechet_decide_bb", (DL_FUNC) &_frechet_internal_frechet_decide_bb, 3},
    {"_frechet_internal_createGridDataset", (DL_FUNC) &_frechet_internal_createGridDataset, 0},
    {"_frechet_internal_addTrajectory", (DL_FUNC) &_frechet_internal_addTrajectory, 2},
    {"_frechet_internal_clearDataset", (DL_FUNC) &_frechet_internal_clearDataset, 1},
    {"_frechet_internal_createIndex_dv", (DL_FUNC) &_frechet_internal_createIndex_dv, 1},
    {"_frechet_internal_gridRangeQuery", (DL_FUNC) &_frechet_internal_gridRangeQuery, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_frechet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
